In [1]:
import numpy as np
import pandas as pd

### sort by index

In [27]:
df = pd.DataFrame(
    {
        "one": pd.Series(np.random.randint(1, 10, size=3), index=['a', 'b', 'c']),
        "two": pd.Series(np.random.randint(1, 10, size=4), index=['b', 'c', 'd', 'e']),
        "three": pd.Series(np.random.randint(1, 10, size=3), index=['c', 'e', 'a']),
    },
)
df

one  two  three
a  8.0  NaN    3.0
b  2.0  3.0    NaN
c  4.0  6.0    3.0
d  NaN  9.0    NaN
e  NaN  9.0    7.0

In [28]:
x = df.reindex(index=['c', 'a', 'd', 'e', 'b'])
x

one  two  three
c  4.0  6.0    3.0
a  8.0  NaN    3.0
d  NaN  9.0    NaN
e  NaN  9.0    7.0
b  2.0  3.0    NaN

In [29]:
x.sort_index()

one  two  three
a  8.0  NaN    3.0
b  2.0  3.0    NaN
c  4.0  6.0    3.0
d  NaN  9.0    NaN
e  NaN  9.0    7.0

In [30]:
x.sort_index(ascending=False)

one  two  three
e  NaN  9.0    7.0
d  NaN  9.0    NaN
c  4.0  6.0    3.0
b  2.0  3.0    NaN
a  8.0  NaN    3.0

In [33]:
x.sort_index(axis=1)

one  three  two
c  4.0    3.0  6.0
a  8.0    3.0  NaN
d  NaN    NaN  9.0
e  NaN    7.0  9.0
b  2.0    NaN  3.0

In [34]:
x['two'].sort_index()

a    NaN
b    3.0
c    6.0
d    9.0
e    9.0
Name: two, dtype: float64

<br>
<br>

MultiIndex...

<br> <br>

### sort by values

In [48]:
df = pd.DataFrame(
    {
        "one": pd.Series(np.random.randint(1, 10, size=4), index=['a', 'b', 'c', 'd']),
        "two": pd.Series(np.random.randint(1, 10, size=4), index=['a', 'b', 'c', 'd']),
        "three": pd.Series(np.random.randint(1, 10, size=4), index=['a', 'b', 'c', 'd']),
    },
    
)
df

one  two  three
a    5    7      4
b    1    9      1
c    9    5      9
d    1    8      4

In [49]:
df.sort_values(by='one')  # sort the df, by the order of 'sorted column a'

one  two  three
b    1    9      1
d    1    8      4
a    5    7      4
c    9    5      9

In [51]:
df.sort_values(by=['one', 'two']) # you can sort by giving multiple columns
                                  # the priority is on sorting the column a

one  two  three
d    1    8      4
b    1    9      1
a    5    7      4
c    9    5      9

In [55]:
df.sort_values(by=list(df.columns))

one  two  three
d    1    8      4
b    1    9      1
a    5    7      4
c    9    5      9

<br> 
<br>

In [59]:
s = pd.Series(
    ["A", "Bcd", "abcd", "hello world", np.nan, "bazinga"],
    dtype='string'
)
s

0              A
1            Bcd
2           abcd
3    hello world
4           <NA>
5        bazinga
dtype: string

In [60]:
s.sort_values()

0              A
1            Bcd
2           abcd
5        bazinga
3    hello world
4           <NA>
dtype: string

you can handle **NaN** :

In [62]:
s.sort_values(na_position='first')

4           <NA>
0              A
1            Bcd
2           abcd
5        bazinga
3    hello world
dtype: string

you can also give a **key** for your sorting :

In [85]:
s = pd.Series(['a', 'F', 'd', 'Z'])
s

0    a
1    F
2    d
3    Z
dtype: object

In [86]:
s.sort_values()

1    F
3    Z
0    a
2    d
dtype: object

In [87]:
s.sort_values(key=lambda x: x.str.lower())

0    a
2    d
1    F
3    Z
dtype: object

In [89]:
df = pd.DataFrame(
    {
        "a": ["B", "a", "C"],
        "b": [1, 2, 3],
    }
)
df

a  b
0  B  1
1  a  2
2  C  3

you can also use **sort_values()** for dafa frames:

In [92]:
df.sort_values(by='a')

a  b
0  B  1
2  C  3
1  a  2

In [93]:
df.sort_values(by='a', key=lambda col: col.str.lower())

a  b
1  a  2
0  B  1
2  C  3

### searchsorted()

In [94]:
s = pd.Series([1, 2, 3])

In [95]:
s.searchsorted([4, 0])

array([3, 0])

in this example if we want to add 0 to the serie, it says the best index for it is 0, so that <br>
it the serie **stayes optimized for searching algorithems**

In [97]:
s.searchsorted([1.5, 2.9])

array([1, 2])

In [98]:
s.searchsorted([0, 3], side='right')

array([0, 3])

In [99]:
s.searchsorted([0, 3], side='left')

array([0, 2])

In [101]:
s.searchsorted([0, 3], sorter=np.argsort(s))

array([0, 2])

### smallest / largest values

In [102]:
s = pd.Series(np.random.randint(1, 10, size=10))
s

0    3
1    6
2    2
3    5
4    3
5    2
6    1
7    9
8    7
9    4
dtype: int64

In [104]:
s.sort_values()

6    1
2    2
5    2
0    3
4    3
9    4
3    5
1    6
8    7
7    9
dtype: int64

In [105]:
s.nsmallest(3)

6    1
2    2
5    2
dtype: int64

In [106]:
s.nlargest(2)

7    9
8    7
dtype: int64

you can also apply for data frames : 

In [123]:
df = pd.DataFrame(
    {
        "a": [2, 4, 1, 5, 0],
        "b": list("aadzb"),
        "c":[1.2, 0.4, np.nan, 22, 0],
    }
)
df

a  b     c
0  2  a   1.2
1  4  a   0.4
2  1  d   NaN
3  5  z  22.0
4  0  b   0.0

In [124]:
df.nlargest(2, 'a')

a  b     c
3  5  z  22.0
1  4  a   0.4

In [125]:
df.nlargest(2, 'c')

a  b     c
3  5  z  22.0
0  2  a   1.2

In [127]:
df.nlargest(2, ['a', 'c'])

a  b     c
3  5  z  22.0
1  4  a   0.4

<br>

Sorting by Multiindex column ...