In [1]:
import numpy as np

In [2]:
x = np.random.randint(10, size=(3, 2))
x

array([[9, 9],
       [0, 4],
       [2, 8]])

In [3]:
np.swapaxes(x, 0, 1)


array([[9, 0, 2],
       [9, 4, 8]])

In [4]:
x.T

array([[9, 0, 2],
       [9, 4, 8]])