## Basic Indexing

In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3, 4, 5])

In [7]:
np.may_share_memory(x[1: 3], x)   # normal indexing is a view

True

___

### difference between x[i] and x[i:i+1]

In [12]:
x = np.random.randint(10, size=(3, 3))
x

array([[2, 1, 2],
       [9, 9, 6],
       [6, 0, 5]])

In [13]:
x[0].shape

(3,)

In [14]:
x[0:1].shape

(1, 3)

___

#### Elispsis

In [22]:
x = np.random.randint(10, size=(4, 4))
x

array([[4, 6, 3, 4],
       [8, 3, 4, 0],
       [4, 3, 6, 9],
       [2, 0, 4, 2]])

In [24]:
x[1:3, 1:3] = -1 # broadcasting
x

array([[ 4,  6,  3,  4],
       [ 8, -1, -1,  0],
       [ 4, -1, -1,  9],
       [ 2,  0,  4,  2]])

___

In [54]:
x = np.random.randint(10, size= (3, 3, 3, 3))

In [56]:
np.all(x[..., 1] == x[:, :, :, 1]) # using ... which is called Ellispsis

True

In [58]:
... == Ellipsis 

True

____

## newaxis


**it's really great for __brodcasting__**

In [3]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [4]:
x[:, np.newaxis]  # pay attention that it is now 2 demmentional

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [5]:
x[np.newaxis, :]

array([[0, 1, 2, 3, 4]])

In [6]:
x[:, np.newaxis]+ x[np.newaxis, :] # this is one use case of broadcasting

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

In [7]:
np.arange(5).reshape(-1, 1) + np.arange(5).reshape(1, -1) # you can also do it like this

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

In [8]:
x + x.reshape(-1, 1)

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

___

## Advance Indexing

* Advanced Indexing results in a copy, not a view

**in Basic indexing, what we have inside the [ ] is a tuple. for example x[1, 2] is simillar to x[(1, 2)]**
**if you put anything but a ( ) inside the brackets, it will be Advance indexing for example : x[[1, 2]]**

**The other case that you get advance indexing is this : x[(1, (1,2)]**
**You have a tuple inside [ ] but whats inside it is a -sequence- and not a number**

the output of each of these cases might be different

In [105]:
x = np.random.randint(10, size=(3, 3, 3))
x

array([[[6, 5, 9],
        [6, 2, 7],
        [9, 0, 2]],

       [[8, 0, 1],
        [5, 3, 0],
        [5, 0, 4]],

       [[4, 2, 7],
        [1, 7, 3],
        [5, 1, 7]]])

In [115]:
x[[1, 2]] # advance indexing

array([[[8, 0, 1],
        [5, 3, 0],
        [5, 0, 4]],

       [[4, 2, 7],
        [1, 7, 3],
        [5, 1, 7]]])

In [118]:
x[(1, 2),] # advance indexing --> because we have sequence inside the tupple

array([[[8, 0, 1],
        [5, 3, 0],
        [5, 0, 4]],

       [[4, 2, 7],
        [1, 7, 3],
        [5, 1, 7]]])

In [114]:
x[(1, (1, 2))] # advance indexing

array([[5, 3, 0],
       [5, 0, 4]])

In [117]:
x[(1, 2)]  # basic indexing

array([5, 0, 4])

In [112]:
np.may_share_memory(x, x[(1, 2)]) # basic indexing

True

In [113]:
np.may_share_memory(x, x[[1, 2]]) # advance indexing

False

#### Boolean array indexing

it's another type of advanced indexing

In [120]:
x = np.array( [
    [1, np.nan],
    [np.nan, 2],
    [3, 4]
])
x

array([[ 1., nan],
       [nan,  2.],
       [ 3.,  4.]])

In [126]:
np.isnan(x)

array([[False,  True],
       [ True, False],
       [False, False]])

In [132]:
# we want to get the elements that are not nan
x[~np.isnan(x)]

array([1., 2., 3., 4.])

In [135]:
# in this example we are going to get the negative numbers from the list and add 5 to them
x = np.random.randint(-10, 10, size=(3, 3))
x

array([[ -4,  -6,  -1],
       [  4,   5, -10],
       [ -4,   8,   3]])

In [138]:
x[x<0] += 5
x

array([[1, 4, 4],
       [4, 5, 0],
       [1, 8, 3]])

In [140]:
# another example : numbers that are divisable by 4
x = np.random.randint(10, size=(3, 3))
x

array([[2, 0, 5],
       [6, 3, 4],
       [7, 8, 4]])

In [142]:
mask = (x%4 == 0) # you can create a mask variable and use it later
mask

array([[False,  True, False],
       [False, False,  True],
       [False,  True,  True]])

In [143]:
x[mask]

array([0, 4, 8, 4])

___
The **normal distribution** is a probability distribution in which roughly 95.45% of values occur within two standard deviations of the mean.

In [145]:
dist = np.random.normal(size=(1, 1000))

In [146]:
std = dist.std()

In [152]:
(len(dist[ (dist<2*std) & (dist>std*-2)]) / 1000) * 100 

95.7

important point here is that we should use **&**   **|** because these two are vectorized operator for such operations <br>
! also pay attention to put the conditions in paranteces !

### Brodcasting

???

In [13]:
x = np.arange(5)
x + x.reshape(-1, 1)

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

___

In [15]:
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])

In [16]:
a

array([1, 2, 3])

In [17]:
b

array([[1],
       [2],
       [3]])

In [20]:
a = a[np.newaxis]
a + b

array([[[2, 3, 4],
        [3, 4, 5],
        [4, 5, 6]]])

In [21]:
# or you could do this instead
a = np.array([1, 2, 3])
a.reshape(1, -1) + b

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])