In [1]:
import numpy as np

## Transpose

In [12]:
x = np.random.randint(10, size=(3,3))
x

array([[4, 7, 3],
       [2, 2, 6],
       [5, 4, 9]])

In [13]:
x.T

array([[4, 2, 5],
       [7, 2, 4],
       [3, 6, 9]])

In [14]:
np.all( (x.T == x.transpose()) )

True

## Sort

In [20]:
np.sort(x) # by default it will sort by axis 1, because it's way faster( check the strides !)

array([[3, 4, 7],
       [2, 2, 6],
       [4, 5, 9]])

In [19]:
np.sort(x, axis=0)

array([[2, 2, 3],
       [4, 4, 6],
       [5, 7, 9]])

In [21]:
np.sort(x, axis=None)

array([2, 2, 3, 4, 4, 5, 6, 7, 9])

___

## Concatination

In [22]:
a = np.random.randint(5, size=(3, 3))
a

array([[4, 4, 3],
       [2, 1, 3],
       [2, 4, 4]])

In [24]:
b = np.random.randint(5, size=(3, 3))
b

array([[1, 0, 4],
       [0, 3, 3],
       [1, 2, 3]])

In [26]:
np.concatenate((a, b), axis=0)

array([[4, 4, 3],
       [2, 1, 3],
       [2, 4, 4],
       [1, 0, 4],
       [0, 3, 3],
       [1, 2, 3]])

In [27]:
np.concatenate((a, b), axis=1)

array([[4, 4, 3, 1, 0, 4],
       [2, 1, 3, 0, 3, 3],
       [2, 4, 4, 1, 2, 3]])

In [28]:
np.vstack((a, b))

array([[4, 4, 3],
       [2, 1, 3],
       [2, 4, 4],
       [1, 0, 4],
       [0, 3, 3],
       [1, 2, 3]])

In [30]:
np.hstack((a, b))

array([[4, 4, 3, 1, 0, 4],
       [2, 1, 3, 0, 3, 3],
       [2, 4, 4, 1, 2, 3]])

In [31]:
np.concatenate((a, b), axis=None)

array([4, 4, 3, 2, 1, 3, 2, 4, 4, 1, 0, 4, 0, 3, 3, 1, 2, 3])