In [2]:
import numpy as np

In [4]:
x = np.dtype('>i4')  # 4 byte integer with big-ending
x

dtype('>i4')

___
### structured data type 

In [12]:
dt = np.dtype([
    ('names', np.unicode_, 16),
    ('grades', np.float64, (2, )),
])

In [13]:
dt.name

'void640'

In [16]:
dt['names']

dtype('<U16')

In [17]:
dt['grades']

dtype(('<f8', (2,)))

In [20]:
obj = np.array([
    ('sarah', (8.0, 7.0)),
    ('john', (6.0, 7.0)),
], dtype=dt)

In [21]:
obj

array([('sarah', [8., 7.]), ('john', [6., 7.])],
      dtype=[('names', '<U16'), ('grades', '<f8', (2,))])

In [29]:
obj['names']

array(['sarah', 'john'], dtype='<U16')

In [32]:
obj['grades']

array([[8., 7.],
       [6., 7.]])

In [35]:
obj[0]['grades']

array([8., 7.])

In [25]:
obj[0][1]

array([8., 7.])