In [1]:
import numpy as np

In [109]:
students = np.array([
    ('ali', 180, 70),
    ('mammad', 160, 75),
    ('ari', 168, 65),
    ('khashi', 173, 60),],
    
    dtype=[
    ('name', 'U14'),
    ('height', 'i8'),
    ('weight', 'i8')])

please pay attention to the [(a,b,c)] part of the expression above: notice the ()? <br>
You're basically telling NumPy to construct an array of 1 element, composed of three sub-elements <br>
(one for each of your a,b,c), each sub-element being an object. If you don't put the (), NumPy will whine a lot.



In [110]:
students['name']

array(['ali', 'mammad', 'ari', 'khashi'], dtype='<U14')

In [111]:
students[0]

('ali', 180, 70)

In [112]:
students[1]

('mammad', 160, 75)

In [113]:
students[1][0]

'mammad'

In [114]:
students[students['height'] > 170]['name']

array(['ali', 'khashi'], dtype='<U14')

In [115]:
students.dtype.names # you can alson change the field names using this

('name', 'height', 'weight')

In [116]:
np.sort(students, order='height')['name']

array(['mammad', 'ari', 'khashi', 'ali'], dtype='<U14')

___

#### Example : Calculating BMI 
*BMI = weight ÷ height$^{2}$*

weight is in kg <br>
height is in meter

In [117]:
students

array([('ali', 180, 70), ('mammad', 160, 75), ('ari', 168, 65),
       ('khashi', 173, 60)],
      dtype=[('name', '<U14'), ('height', '<i8'), ('weight', '<i8')])

In [118]:
students_bmi = np.array(students['weight'] / (students['height']/100)**2, dtype=[('bmi', np.float32)])
students_bmi

array([(21.604939,), (29.296875,), (23.030045,), (20.047445,)],
      dtype=[('bmi', '<f4')])

In [119]:
import numpy.lib.recfunctions as rfn

In [120]:
students = rfn.merge_arrays((students, students_bmi), flatten = True, usemask = False)
students

array([('ali', 180, 70, 21.604939), ('mammad', 160, 75, 29.296875),
       ('ari', 168, 65, 23.030045), ('khashi', 173, 60, 20.047445)],
      dtype=[('name', '<U14'), ('height', '<i8'), ('weight', '<i8'), ('bmi', '<f4')])

In [139]:
np.sort(students[['name', 'bmi']], order='bmi')

array([('khashi', 20.047445), ('ali', 21.604939), ('ari', 23.030045),
       ('mammad', 29.296875)],
      dtype={'names':['name','bmi'], 'formats':['<U14','<f4'], 'offsets':[0,72], 'itemsize':76})

___
#### record_array vs structure_array

suppose we have these datas

In [4]:
id_ = np.arange(1, 11)
id_

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
heights = np.random.randint(150, 200, size=10)
heights

array([172, 160, 172, 169, 165, 154, 159, 190, 172, 160])

In [13]:
weights = np.random.randint(50, 100, size=10)
weights

array([72, 91, 70, 56, 56, 74, 99, 66, 64, 64])

##### using record_array

In [25]:
rec_data = np.core.records.fromarrays(
    [id_, heights, weights],
    names='id, heights, weights',
    formats= 'i8, i8, i8'
)
rec_data

rec.array([( 1, 172, 72), ( 2, 160, 91), ( 3, 172, 70), ( 4, 169, 56),
           ( 5, 165, 56), ( 6, 154, 74), ( 7, 159, 99), ( 8, 190, 66),
           ( 9, 172, 64), (10, 160, 64)],
          dtype=[('id', '<i8'), ('heights', '<i8'), ('weights', '<i8')])

In [28]:
rec_data[['id', 'heights']]

rec.array([( 1, 172), ( 2, 160), ( 3, 172), ( 4, 169), ( 5, 165),
           ( 6, 154), ( 7, 159), ( 8, 190), ( 9, 172), (10, 160)],
          dtype={'names':['id','heights'], 'formats':['<i8','<i8'], 'offsets':[0,8], 'itemsize':24})

##### using structure_array

In [29]:
struct_array = np.array(
    list(zip(id_, heights, weights)),
    dtype=[
        ('id', 'i8'),
        ('heights', 'i8'),
        ('weights', 'i8'),])
struct_array

array([( 1, 172, 72), ( 2, 160, 91), ( 3, 172, 70), ( 4, 169, 56),
       ( 5, 165, 56), ( 6, 154, 74), ( 7, 159, 99), ( 8, 190, 66),
       ( 9, 172, 64), (10, 160, 64)],
      dtype=[('id', '<i8'), ('heights', '<i8'), ('weights', '<i8')])

In [30]:
struct_array[['id', 'heights']]

array([( 1, 172), ( 2, 160), ( 3, 172), ( 4, 169), ( 5, 165), ( 6, 154),
       ( 7, 159), ( 8, 190), ( 9, 172), (10, 160)],
      dtype={'names':['id','heights'], 'formats':['<i8','<i8'], 'offsets':[0,8], 'itemsize':24})