## Matrix Class

In [1]:
import numpy as np

In [2]:
nd_array = np.arange(9).reshape((3, 3))

In [4]:
x = np.matrix(nd_array)
x

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [7]:
y = np.mat(np.identity(3)) # np.matrix(np.identity(3))
y

matrix([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

numpy.matrix() creates a <ins>copy</ins><br> while numpy.mat() changes the <ins>view</ins> only; it's equivalent to numpy.matrix(data, copy = False).

##### other ways of creating a matrix

In [8]:
np.matrix('1 2 3; 4 5 6; 7 8 9')

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [10]:
np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

other operations are written on pytopia github

## Polynomial mathematics


##### calculating the coefficients of a polynomial:

In [11]:
root = np.array([1, 2, 3, 4])

In [12]:
np.poly(root)

array([  1., -10.,  35., -50.,  24.])

##### calculating the roots based on the coefficients

In [13]:
np.roots(np.array([  1., -10.,  35., -50.,  24.]))

array([4., 3., 2., 1.])

Now, let's say we have the equation , and we want to know the value of y when x = 5. We can use numpy.polyval() to calculate this:

In [16]:
np.polyval(np.array([  1., -10.,  35., -50.,  24.]), x=2) # it returns 0 because x=2 is one of our roots

0.0

#### integrals and derivative

In [18]:
coef = np.array([  1., -10.,  35., -50.,  24.])

In [24]:
integral = np.polyint(coef)
integral

array([  0.2       ,  -2.5       ,  11.66666667, -25.        ,
        24.        ,   0.        ])

In [29]:
derivative = np.polyder(integral)
derivative

array([  1., -10.,  35., -50.,  24.])

In [31]:
(derivative == coef).all() # because we know that derivative of the integral is equals to the poylinomial itself

True